title: AmericaSCORESBayArea - GitHub
email: support@americascoresbayarea.org
description: >- # this means to ignore newlines until "baseurl:"
  This website contains list of all the open source repositories on github by AmericaSCORESBayArea.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
about_url: 
twitter_username: 
github_username: 
author: CritiqalPete
lang: en-IN
google_analytics: 

timezone: 

# Build settings
markdown: kramdown
plugins:
#  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
#  - jekyll-mentions
#  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
